// src/pages/Login.svelte
<script lang="ts">
  import { push, querystring } from 'svelte-spa-router'
  import { useAuthStore } from '@/stores/auth-store'

  let isLoaded = $derived(!$useAuthStore.checking)
  let isSignedIn = $derived($useAuthStore.isSignedIn)
  let target = $derived(new URLSearchParams($querystring ?? '').get('redirect') || '/')

  $effect(() => {
    if (isLoaded && isSignedIn) push(target)
    else if (isLoaded && !isSignedIn) {
      window.location.replace(`https://me.mcky.space?from=data&redirect=${encodeURIComponent(target)}`)
    }
  })
</script>

<div style="min-height: 100dvh; display: flex; align-items: center; justify-content: center; background: var(--bg);">
  <div style="color: var(--muted); font-size: 13px">กำลังนำทางไปยังหน้าเข้าสู่ระบบ...</div>
</div>

// src/pages/Login.tsx
import { useEffect } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { useAdminAuth } from '@/stores/auth-store'

export function Login() {
  const navigate = useNavigate()
  const location = useLocation()
  const { isLoaded, isSignedIn } = useAdminAuth()

  const target = new URLSearchParams(location.search).get('redirect') || '/'

  useEffect(() => {
    if (isLoaded && isSignedIn) navigate(target, { replace: true })
  }, [isLoaded, isSignedIn, navigate, target])

  useEffect(() => {
    if (isLoaded && !isSignedIn) {
      const portalUrl = `https://me.mcky.space?from=data&redirect=${encodeURIComponent(target)}`
      window.location.replace(portalUrl)
    }
  }, [isLoaded, isSignedIn, target])

  return (
    <div
      style={{
        minHeight: '100dvh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'var(--bg)',
      }}
    >
      <div style={{ color: 'var(--muted)', fontSize: 13 }}>
        กำลังนำทางไปยังหน้าเข้าสู่ระบบ...
      </div>
    </div>
  )
}
