// src/components/MapPicker.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { OpenLocationCode } from 'open-location-code'
  import { pinHtml } from '@/lib/pin'
  import { getTileUrl, TILE_ATTRIBUTION, TILE_MAX_ZOOM, isDarkMode, KHON_KAEN_CENTER, KHON_KAEN_BOUNDS, KHON_KAEN_MIN_ZOOM } from '@/lib/map-styles'
  import { cssVarToHex } from '@/lib/utils'
  import { observeMapDarkMode } from '@/lib/map-dark-mode'

  let { lat, lng, onChange }: { lat: number | null; lng: number | null; onChange: (lat: number, lng: number) => void } = $props()

  type LL = typeof import('leaflet')
  async function loadLeaflet(): Promise<LL> {
    const [mod] = await Promise.all([import('leaflet'), import('leaflet/dist/leaflet.css')])
    return (mod.default ?? mod) as LL
  }
  let olcInstance: OpenLocationCode | null = null
  function getOlc() {
    if (!olcInstance) olcInstance = new OpenLocationCode()
    return olcInstance
  }
  const getPinColor = () => cssVarToHex('--pin-color', '#2563eb')
  const PIN_ZOOM = 16
  const PROVINCE_ZOOM = 11

  let containerRef: HTMLDivElement
  let map: InstanceType<LL['Map']> | null = null
  let layer: InstanceType<LL['TileLayer']> | null = null
  let marker: InstanceType<LL['Marker']> | null = null
  let lib: LL | null = null
  let mapFailed = $state(false)
  let dark = $state(isDarkMode())
  let attrOpen = $state(false)
  let initialized = false
  let onChangeCb = onChange
  $effect(() => {
    onChangeCb = onChange
  })
  let latRef = lat
  let lngRef = lng
  $effect(() => {
    latRef = lat
    lngRef = lng
  })

  function placeMarker(mlat: number, mlng: number) {
    if (!lib || !map) return
    marker?.remove()
    const el = document.createElement('div')
    el.innerHTML = pinHtml(28, true, getPinColor())
    marker = lib.marker([mlat, mlng], { icon: lib.divIcon({ html: el, className: '', iconSize: [28, 28], iconAnchor: [14, 25] }) }).addTo(map)
  }

  $effect(() => {
    layer?.setUrl(getTileUrl(dark), true)
  })

  onMount(() => {
    let cancelled = false
    const unsubDark = observeMapDarkMode((d) => (dark = d))
    ;(async () => {
      let L: LL
      try {
        L = await loadLeaflet()
      } catch {
        if (!cancelled) mapFailed = true
        return
      }
      if (cancelled || !L?.map || !containerRef) return
      lib = L
      try {
        const hasPos = lngRef != null && latRef != null
        const m = L.map(containerRef, {
          attributionControl: false,
          minZoom: KHON_KAEN_MIN_ZOOM,
          maxBounds: [[KHON_KAEN_BOUNDS[0][1], KHON_KAEN_BOUNDS[0][0]], [KHON_KAEN_BOUNDS[1][1], KHON_KAEN_BOUNDS[1][0]]],
          maxBoundsViscosity: 1.0,
        }).setView(hasPos ? [latRef as number, lngRef as number] : [KHON_KAEN_CENTER[1], KHON_KAEN_CENTER[0]], hasPos ? PIN_ZOOM : PROVINCE_ZOOM)
        layer = L.tileLayer(getTileUrl(dark), { maxZoom: TILE_MAX_ZOOM, detectRetina: true, attribution: TILE_ATTRIBUTION }).addTo(m)
        m.on('click', (e) => {
          const { lat: mlat, lng: mlng } = e.latlng
          onChangeCb(mlat, mlng)
          m.flyTo([mlat, mlng], Math.max(m.getZoom(), PIN_ZOOM), { duration: 0.6 })
          placeMarker(mlat, mlng)
        })
        if (latRef != null && lngRef != null) {
          initialized = true
          placeMarker(latRef, lngRef)
        }
        map = m
        setTimeout(() => {
          if (!cancelled) m.invalidateSize()
        }, 100)
      } catch {
        if (!cancelled) mapFailed = true
      }
    })()
    return () => {
      cancelled = true
      unsubDark()
      try {
        map?.remove()
      } catch {}
      map = null
      lib = null
      layer = null
      marker = null
    }
  })

  $effect(() => {
    const m = map
    if (!m || lat == null || lng == null) return
    if (!initialized) {
      initialized = true
      if (lat !== KHON_KAEN_CENTER[1] || lng !== KHON_KAEN_CENTER[0]) m.flyTo([lat, lng], PIN_ZOOM, { duration: 0.6 })
      if (!marker) placeMarker(lat, lng)
      return
    }
    if (marker) marker.setLatLng([lat, lng])
    else placeMarker(lat, lng)
    m.flyTo([lat, lng], Math.max(m.getZoom(), PIN_ZOOM), { duration: 0.6 })
  })
</script>

{#if mapFailed}
  <div class="w-full h-48 rounded-xl overflow-hidden border border-border bg-card flex items-center justify-center text-muted-foreground text-xs">ไม่สามารถโหลดแผนที่ได้</div>
{:else}
  <div class="w-full h-48 rounded-xl overflow-hidden border border-border relative">
    <div bind:this={containerRef} class="w-full h-full z-0"></div>
    {#if lat != null && lng != null}
      <div class="absolute bottom-1 left-1/2 -translate-x-1/2 z-10 px-2 py-0.5 rounded-md bg-background/80 backdrop-blur-sm text-[13px] font-mono text-foreground whitespace-nowrap pointer-events-none flex items-center gap-1.5">
        <span class="text-foreground/90">{lat.toFixed(4)}, {lng.toFixed(4)}</span>
        <span class="text-foreground/30">|</span>
        <span class="text-success font-bold tracking-wider">{getOlc().encode(lat, lng, 10)}</span>
      </div>
    {/if}
    <div class="absolute bottom-1 right-1 z-10 flex items-center gap-1">
      <span class="rounded-md bg-black/70 px-2 py-1 font-mono text-[9px] leading-none text-white backdrop-blur {attrOpen ? '' : 'hidden'}">{TILE_ATTRIBUTION}</span>
      <button type="button" onclick={(e) => { e.stopPropagation(); attrOpen = !attrOpen }} aria-label={attrOpen ? 'ซ่อนเครดิต' : 'แสดงเครดิต'} class="flex h-11 w-11 items-center justify-center rounded-full bg-black/60 text-[10px] font-bold text-white backdrop-blur hover:bg-black/70">©</button>
    </div>
  </div>
{/if}

// src/components/MapPicker.tsx

import { useEffect, useRef, useCallback, useState } from 'react'
import maplibregl from 'maplibre-gl'
import 'maplibre-gl/dist/maplibre-gl.css'
import { OpenLocationCode } from 'open-location-code'
import { pinHtml } from '@/lib/pin'
import { getMapStyle } from '@/lib/map-styles'
import { cssVarToHex } from '@/lib/utils'
import { useMapDarkMode } from '@/hooks/useMapDarkMode'

let olcInstance: OpenLocationCode | null = null
function getOlc(): OpenLocationCode {
  if (!olcInstance) olcInstance = new OpenLocationCode()
  return olcInstance
}

const DEFAULT_CENTER: [number, number] = [102.8236, 16.4322]

function getPinColor(): string {
  return cssVarToHex('--pin-color', '#2563eb')
}

const DEFAULT_ZOOM = 8
const PIN_ZOOM = 16

export interface MapPickerProps {
  lat: number | null
  lng: number | null
  onChange: (lat: number, lng: number) => void
}

type Props = MapPickerProps

export default function MapPicker({ lat, lng, onChange }: Props) {
  const containerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<maplibregl.Map | null>(null)
  const markerRef = useRef<maplibregl.Marker | null>(null)
  const [mapFailed, setMapFailed] = useState(false)
  const initializedRef = useRef(false)
  const onChangeRef = useRef(onChange)
  const latRef = useRef(lat)
  const lngRef = useRef(lng)

  useEffect(() => { onChangeRef.current = onChange })
  useEffect(() => { latRef.current = lat; lngRef.current = lng }, [lat, lng])

  useEffect(() => {
    if (!containerRef.current || mapRef.current) return

    let map: maplibregl.Map
    try {
      map = new maplibregl.Map({
        container: containerRef.current,
        style: getMapStyle(),
        center: lngRef.current != null && latRef.current != null ? [lngRef.current, latRef.current] : DEFAULT_CENTER,
        zoom: latRef.current != null ? PIN_ZOOM : DEFAULT_ZOOM,
        attributionControl: false,
      })
    } catch (err) {
      console.error('MapPicker init failed', err)
      setMapFailed(true)
      return
    }

    map.on('click', (e) => {
      const { lng: mlng, lat: mlat } = e.lngLat
      onChangeRef.current(mlat, mlng)
      map.flyTo({ center: [mlng, mlat], zoom: Math.max(map.getZoom(), PIN_ZOOM), duration: 600 })

      if (markerRef.current) markerRef.current.remove()
      const el = document.createElement('div')
      el.innerHTML = pinHtml(28, true, getPinColor())
      markerRef.current = new maplibregl.Marker({ element: el }).setLngLat([mlng, mlat]).addTo(map)
    })

    // Add initial marker if position provided
    if (latRef.current != null && lngRef.current != null) {
      initializedRef.current = true
      const el = document.createElement('div')
      el.innerHTML = pinHtml(28, true, getPinColor())
      markerRef.current = new maplibregl.Marker({ element: el }).setLngLat([lngRef.current, latRef.current]).addTo(map)
    }

    mapRef.current = map

    return () => {
      map.remove()
      mapRef.current = null
    }
  }, [])

  useMapDarkMode(
    useCallback((newStyle) => {
      const map = mapRef.current
      if (!map) return
      map.setStyle(newStyle)
      map.once('style.load', () => {
        if (markerRef.current) {
          const pos = markerRef.current.getLngLat()
          markerRef.current.remove()
          const el = document.createElement('div')
          el.innerHTML = pinHtml(28, true, getPinColor())
          markerRef.current = new maplibregl.Marker({ element: el }).setLngLat(pos).addTo(map)
        }
      })
    }, []),
  )

  // Update marker and fly when lat/lng change externally
  useEffect(() => {
    const map = mapRef.current
    if (!map || lat == null || lng == null) return

    if (!initializedRef.current) {
      initializedRef.current = true
      if (lat !== DEFAULT_CENTER[1] || lng !== DEFAULT_CENTER[0]) {
        map.flyTo({ center: [lng, lat], zoom: PIN_ZOOM, duration: 600 })
      }
      if (!markerRef.current) {
        const el = document.createElement('div')
        el.innerHTML = pinHtml(28, true, getPinColor())
        markerRef.current = new maplibregl.Marker({ element: el }).setLngLat([lng, lat]).addTo(map)
      }
      return
    }

    if (markerRef.current) {
      markerRef.current.setLngLat([lng, lat])
    } else {
      const el = document.createElement('div')
      el.innerHTML = pinHtml(28, true, getPinColor())
      markerRef.current = new maplibregl.Marker({ element: el }).setLngLat([lng, lat]).addTo(map)
    }

    map.flyTo({ center: [lng, lat], zoom: Math.max(map.getZoom(), PIN_ZOOM), duration: 600 })
  }, [lat, lng])

  if (mapFailed) {
    return (
      <div className="w-full h-48 rounded-xl overflow-hidden border border-border bg-card flex items-center justify-center text-muted-foreground text-xs">
        ไม่สามารถโหลดแผนที่ได้
      </div>
    )
  }

  return (
    <div className="w-full h-48 rounded-xl overflow-hidden border border-border relative">
      <div ref={containerRef} className="w-full h-full" />
      {lat != null && lng != null && (
        <div className="absolute bottom-1 left-1/2 -translate-x-1/2 z-10 px-2 py-0.5 rounded-md bg-background/80 backdrop-blur-sm text-[13px] font-mono text-foreground whitespace-nowrap pointer-events-none flex items-center gap-1.5">
          <span className="text-foreground/90">
            {lat.toFixed(4)}, {lng.toFixed(4)}
          </span>
          <span className="text-foreground/30">|</span>
          <span className="text-success font-bold tracking-wider">
            {getOlc().encode(lat, lng, 10)}
          </span>
        </div>
      )}
    </div>
  )
}
