// src/components/AppImage.svelte
<script lang="ts">

  let {
    src,
    alt,
    fallbackSrc,
    onerror,
    className,
    ...rest
  }: {
    src: string
    alt: string
    fallbackSrc?: string
    className?: string
    onerror?: (e: Event & { currentTarget: Element }) => void
    [key: string]: unknown
  } = $props()

  let current = $state(src)
  let prevSrc = $state(src)
  $effect(() => {
    if (src !== prevSrc) {
      prevSrc = src
      current = src
    }
  })
</script>

<img
  src={current}
  {alt}
  loading="lazy"
  decoding="async"
  class={className}
  onerror={(e) => {
    if (fallbackSrc && current !== fallbackSrc) current = fallbackSrc
    onerror?.(e)
  }}
  {...rest}
/>

// src-react-legacy/components/AppImage.tsx
import { useState } from 'react'

interface AppImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  src: string
  alt: string
  /** One-time fallback (e.g. full-size photo) if `src` 404s — used for
   *  list thumbnails of photos uploaded before thumbs existed. */
  fallbackSrc?: string
}

export default function AppImage({ src, alt, fallbackSrc, onError, ...rest }: AppImageProps) {
  const [current, setCurrent] = useState(src)
  // Reset when the parent switches to a different photo.
  const [prevSrc, setPrevSrc] = useState(src)
  if (src !== prevSrc) {
    setPrevSrc(src)
    setCurrent(src)
  }
  return (
    <img
      src={current}
      alt={alt}
      loading="lazy"
      decoding="async"
      onError={(e) => {
        if (fallbackSrc && current !== fallbackSrc) {
          setCurrent(fallbackSrc)
        }
        onError?.(e)
      }}
      {...rest}
    />
  )
}
