// src/App.tsx
import { lazy, Suspense, useEffect } from 'react'
import { Routes, Route, useLocation, NavLink, useNavigate } from 'react-router-dom'
import { useAuth } from '@clerk/clerk-react'
import { ArrowClockwise, House, Plus, Gear, MapTrifold, Trash } from '@phosphor-icons/react'
import { Loading } from '@/components/Loading'
import { AuthSync } from '@/components/AuthSync'
import { useClientStore } from '@/stores/client-store'
import { useAuthStore } from '@/stores/auth-store'
import { useAppTheme } from '@/lib/app-theme'
import { isFormDirty } from '@/lib/form-dirty'
import CommandPalette from '@/components/CommandPalette'
import { SyncStatus } from '@/components/SyncStatus'
import '@/styles/ledger.css'

const CatalogPage = lazy(() => import('@/pages/Catalog'))
const RecordPage = lazy(() => import('@/pages/Record'))
const EditorPage = lazy(() => import('@/pages/Editor'))
const TrashPage = lazy(() => import('@/pages/Trash'))
const MapsPage = lazy(() => import('@/pages/Maps'))
const NotFoundPage = lazy(() => import('@/pages/NotFound'))
const SettingsPage = lazy(() => import('@/pages/Settings'))
const LoginPage = lazy(() => import('@/pages/Login').then(module => ({ default: module.Login })))
const DetailLab = lazy(() => import('@/__design_lab/detail/lab/DetailLabApp'))

function App() {
  const location = useLocation()
  const navigate = useNavigate()
  const { isAdmin, loginOpen } = useAuthStore()
  const { isLoaded, isSignedIn } = useAuth()
  const { themeId, mode, resolvedMode, customPalette, setThemeId, setMode, setCustomPalette } = useAppTheme()

  useEffect(() => { void useClientStore.getState().initialize() }, [])
  useEffect(() => { document.getElementById('ledger-main')?.scrollTo({ top: 0 }) }, [location.pathname])

  const guardNavigation = (event: React.MouseEvent) => {
    if (isFormDirty() && !window.confirm('มีข้อมูลที่ยังไม่บันทึก ต้องการออกจากฟอร์มไหม?')) {
      event.preventDefault()
      event.stopPropagation()
    }
  }

  const wantsLogin = location.pathname === '/login' || loginOpen
  if (wantsLogin && isLoaded && !isSignedIn) {
    return <Suspense fallback={<Loading />}><LoginPage /></Suspense>
  }

  if (location.pathname.startsWith('/__design_lab/detail')) {
    return <Suspense fallback={<Loading />}><DetailLab /></Suspense>
  }

  return (
    <div className="ledger-shell" data-mode={resolvedMode}>
      <AuthSync />
      <div className="pointer-events-none fixed right-3 top-[env(safe-area-top)] z-40 pt-3 sm:right-5">
        <div className="pointer-events-auto"><SyncStatus /></div>
      </div>
      <a href="#ledger-main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-card focus:px-4 focus:py-3 focus:text-foreground">ข้ามไปเนื้อหา</a>
      <main id="ledger-main" className="ledger-main min-h-0 flex-1 overflow-y-auto overscroll-contain">
        <Suspense fallback={<Loading />}>
          <Routes>
            <Route path="/" element={<CatalogPage />} />
            <Route path="/add" element={<EditorPage />} />
            <Route path="/edit/:id" element={<EditorPage />} />
            <Route path="/trash" element={<TrashPage />} />
            <Route path="/maps" element={<MapsPage />} />
            <Route path="/settings" element={<SettingsPage mode={mode} setMode={setMode} themeId={themeId} setThemeId={setThemeId} customPalette={customPalette} setCustomPalette={setCustomPalette} />} />
            <Route path="/c/:id" element={<RecordPage />} />
            <Route path="*" element={<NotFoundPage />} />
          </Routes>
        </Suspense>
      </main>
      <nav className="ledger-bottom-nav relative z-50 shrink-0 border-t border-border bg-card/95 backdrop-blur" aria-label="หลัก">
        <div className="mx-auto flex h-[4.5rem] max-w-xl items-center justify-around px-3 pb-[env(safe-area-bottom)]">
          <NavLink to="/" end onClick={guardNavigation} aria-label="หน้าหลัก" className={({ isActive }) => `ledger-nav-item ${isActive ? 'is-active' : ''}`}><House weight="fill" size={21} aria-hidden /><span>หน้าหลัก</span></NavLink>
          <NavLink to="/maps" onClick={guardNavigation} aria-label="แผนที่" className={({ isActive }) => `ledger-nav-item ${isActive ? 'is-active' : ''}`}><MapTrifold size={21} aria-hidden /><span>แผนที่</span></NavLink>
          <NavLink to="/trash" onClick={guardNavigation} aria-label="ถังขยะ" className={({ isActive }) => `ledger-nav-item ${isActive ? 'is-active' : ''}`}><Trash size={21} aria-hidden /><span>ถังขยะ</span></NavLink>
          <button type="button" onClick={event => { if (isFormDirty() && !window.confirm('มีข้อมูลที่ยังไม่บันทึก ต้องการรีเฟรชหน้าไหม?')) { event.preventDefault(); return } window.location.reload() }} aria-label="รีเฟรชหน้า" className="ledger-nav-item"><ArrowClockwise size={21} aria-hidden /><span>รีเฟรช</span></button>
          <button type="button" onClick={event => { guardNavigation(event); if (!event.defaultPrevented) navigate('/settings') }} aria-label="เมนูและการตั้งค่า" className={`ledger-nav-item ${location.pathname === '/settings' ? 'is-active' : ''}`}><Gear size={21} aria-hidden /><span>เมนู</span></button>
          {isAdmin ? <NavLink to="/add" onClick={guardNavigation} aria-label="เพิ่มรายการ" className="ledger-add-button"><Plus weight="bold" size={25} aria-hidden /></NavLink> : <span aria-label="เพิ่มรายการ" aria-disabled="true" className="ledger-add-button opacity-40 bg-muted text-muted-foreground border border-border grayscale"><Plus weight="bold" size={25} aria-hidden /></span>}
        </div>
      </nav>
      <CommandPalette />
    </div>
  )
}

export default App

// src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import Router, { location, link, push } from 'svelte-spa-router'
  import { ArrowClockwise, House, Plus, Gear, MapTrifold, Trash } from 'phosphor-svelte'
  import { useAuthStore } from '@/stores/auth-store'
  import { useClientStore } from '@/stores/client-store'
  import { isFormDirty } from '@/lib/form-dirty'
  import { appTheme, initAppTheme } from '@/lib/app-theme'
  import { initClerk } from '@/lib/clerk'
  import { flushClientMutations } from '@/lib/offline-mutations'
  import CommandPalette from '@/components/CommandPalette.svelte'
  import UpdatePrompt from '@/components/UpdatePrompt.svelte'
  import '@/styles/ledger.css'

  import Login from './pages/Login.svelte'

  const Catalog = () => import('./pages/Catalog.svelte')
  const Record = () => import('./pages/Record.svelte')
  const Editor = () => import('./pages/Editor.svelte')
  const TrashPage = () => import('./pages/Trash.svelte')
  const Maps = () => import('./pages/Maps.svelte')
  const Settings = () => import('./pages/Settings.svelte')
  const NotFound = () => import('./pages/NotFound.svelte')

  const routes = {
    '/': Catalog,
    '/add': Editor,
    '/edit/:id': Editor,
    '/trash': TrashPage,
    '/maps': Maps,
    '/settings': Settings,
    '/c/:id': Record,
    '/login': Login,
    '*': NotFound,
  }

  let theme = $derived($appTheme)
  let isAdmin = $derived($useAuthStore.isAdmin)
  let checking = $derived($useAuthStore.checking)
  let signedIn = $derived($useAuthStore.isSignedIn)
  let loginOpen = $derived($useAuthStore.loginOpen)

  onMount(() => {
    initAppTheme()
    void initClerk()
    void useClientStore.getState().initialize()
    const flush = () => {
      const userId = useAuthStore.getState().userId
      if (userId) void flushClientMutations(userId)
    }
    window.addEventListener('online', flush)
    flush()
    const unsub = location.subscribe(() => {
      document.getElementById('ledger-main')?.scrollTo({ top: 0 })
    })
    return () => {
      window.removeEventListener('online', flush)
      unsub()
    }
  })

  function guardNavigation(event: MouseEvent): void {
    if (isFormDirty() && !window.confirm('มีข้อมูลที่ยังไม่บันทึก ต้องการออกจากฟอร์มไหม?')) {
      event.preventDefault()
      event.stopPropagation()
    }
  }

  const wantsLogin = $derived($location === '/login' || loginOpen)
</script>

{#if wantsLogin && !checking && !signedIn}
  <Login />
{:else}
  <div class="ledger-shell" data-mode={theme.resolvedMode}>
    <a href="#ledger-main" class="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-card focus:px-4 focus:py-3 focus:text-foreground">ข้ามไปเนื้อหา</a>
    <main id="ledger-main" class="ledger-main min-h-0 flex-1 overflow-y-auto overscroll-contain">
      <svelte:boundary onerror={(e) => console.error(e)}>
        <Router {routes} />
        {#snippet failed(error)}
          <div class="p-8 text-sm text-destructive">{(error as Error)?.message ?? 'เกิดข้อผิดพลาด'}</div>
        {/snippet}
      </svelte:boundary>
    </main>
    <nav class="ledger-bottom-nav relative z-50 shrink-0 border-t border-border bg-card/95 backdrop-blur" aria-label="หลัก">
      <div class="mx-auto flex h-[4.5rem] max-w-xl items-center justify-around px-3 pb-[env(safe-area-bottom)]">
        <a href="/" use:link onclick={guardNavigation} aria-label="หน้าหลัก" class="ledger-nav-item" class:is-active={$location === '/'} tabindex="0"><House weight="fill" size={21} aria-hidden /><span>หน้าหลัก</span></a>
        <a href="/maps" use:link onclick={guardNavigation} aria-label="แผนที่" class="ledger-nav-item" class:is-active={$location === '/maps'}><MapTrifold size={21} aria-hidden /><span>แผนที่</span></a>
        <a href="/trash" use:link onclick={guardNavigation} aria-label="ถังขยะ" class="ledger-nav-item" class:is-active={$location === '/trash'}><Trash size={21} aria-hidden /><span>ถังขยะ</span></a>
        <button type="button" onclick={() => window.location.reload()} aria-label="รีเฟรชหน้า" class="ledger-nav-item"><ArrowClockwise size={21} aria-hidden /><span>รีเฟรช</span></button>
        <button type="button" onclick={(e) => { guardNavigation(e); if (!e.defaultPrevented) push('/settings') }} aria-label="เมนูและการตั้งค่า" class="ledger-nav-item" class:is-active={$location === '/settings'}><Gear size={21} aria-hidden /><span>เมนู</span></button>
        {#if isAdmin}
          <a href="/add" use:link onclick={guardNavigation} aria-label="เพิ่มรายการ" class="ledger-add-button"><Plus weight="bold" size={25} aria-hidden /></a>
        {:else}
          <span aria-label="เพิ่มรายการ" aria-disabled="true" class="ledger-add-button opacity-40 bg-muted text-muted-foreground border border-border grayscale"><Plus weight="bold" size={25} aria-hidden /></span>
        {/if}
      </div>
    </nav>
    <CommandPalette />
    <UpdatePrompt />
  </div>
{/if}
